config/routes.rb
Rails.application.routes.draw do
  get 'characters/index'
    resources :characters do
      resources :comments
    end
  root 'characters#index'
end

app/models/character.rb
class Character < ApplicationRecord
    has_many :comments
    #validates :name, presence: true, length: { minimum: 3 }
    #validates_presence_of :background, :message => "It may be a mystery where they came from, but not so much so that there is nothing to put."
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
    @@race = "temp"
    @@classes = "temp"
    @@strength = 0           #0
    @@dexterity = 0          #1
    @@constitution = 0       #2
    @@intelligence = 0       #3
    @@wisdom = 0             #4
    @@charisma = 0           #5
    @@armorclass = "temp"
    @@gold = 0
    @@hitpoints = 0
    @@strengthmodifier = 0           #0
    @@dexteritymodifier = 0          #1
    @@constitutionmodifier = 0       #2
    @@intelligencemodifier = 0       #3
    @@wisdommodifier = 0             #4
    @@charismamodifier = 0           #5
    @@armorequipment = "temp"
    @@weaponequipment = "temp"
    
    def index
        @characters = Character.all
    end
    
    def show
        @character = Character.find(params[:id])
    end
    
    def new
        @character = Character.new
    end
    
    def create
        @character = Character.new(character_params)
        @@armorclass = "God Armor"
        @@strength = characterStats
        @@dexterity = characterStats
        @@constitution = characterStats
        @@intelligence = characterStats
        @@wisdom = characterStats
        @@charisma = characterStats
        raceGeneration
        @@strengthmodifier = characterModifier(@@strength)
        @@dexteritymodifier = characterModifier(@@dexterity)
        @@constitutionmodifier = characterModifier(@@constitution)
        @@intelligencemodifier = characterModifier(@@intelligence)
        @@wisdommodifier = characterModifier(@@wisdom)
        @@charismamodifier = characterModifier(@@charisma)
        classGeneration
        
        @character.race = @@race
        @character.classes = @@classes
        @character.strength = @@strength
        @character.dexterity = @@dexterity
        @character.constitution = @@constitution
        @character.intelligence = @@intelligence
        @character.wisdom = @@wisdom
        @character.charisma = @@charisma
        @character.armorclass = @@armorclass
        @character.gold = @@gold
        @character.hitpoints = @@hitpoints
        @character.strengthmodifier = @@strengthmodifier
        @character.dexteritymodifier = @@dexteritymodifier
        @character.constitutionmodifier = @@constitutionmodifier
        @character.intelligencemodifier = @@intelligencemodifier
        @character.wisdommodifier = @@wisdommodifier
        @character.charismamodifier = @@charismamodifier
        @character.armorequipment = @@armorequipment
        @character.weaponequipment = @@weaponequipment
        
        if @character.save
            redirect_to @character
        else
            render 'new'
        end
    end
  
    def edit
        @character = Character.find(params[:id])
    end
  
    def update
        @character = Character.find(params[:id])
    
        if @character.update(character_params)
            redirect_to @character
        else
            render 'edit'
        end
    end
  
    def destroy
        @character = Character.find(params[:id])
        @character.destroy

        redirect_to characters_path
    end

private
    def characterStats
        @firstRoll = rand(1..6)
        @secondRoll = rand(1..6)
        @thirdRoll = rand(1..6)
        @fourthRoll = rand(1..6)
        @stats = [@firstRoll, @secondRoll, @thirdRoll, @fourthRoll]
        @stats.sort
        @total = @stats[1] + @stats[2] + @stats[3]
    end
    
    def characterModifier(stat)
        if(stat == 1)
            @modifier = -5
        elsif stat == 2 || stat == 3
            @modifier = -4
        elsif stat == 4 || stat == 5
            @modifier = -3
        elsif stat == 6 || stat == 7
            @modifier = -2
        elsif stat == 8 || stat == 9
            @modifier = -1
        elsif stat == 10 || stat == 11
            @modifier = 0
        elsif stat == 12 || stat == 13
            @modifier = 1
        elsif stat == 14 || stat == 15
            @modifier = 2
        elsif stat == 16 || stat == 17
            @modifier = 3
        elsif stat == 18 || stat == 19
            @modifier = 4
        elsif stat == 20 || stat == 21
            @modifier = 5
        elsif stat == 22 || stat == 23
            @modifier = 6
        elsif stat == 24 || stat == 25
            @modifier = 7
        elsif stat == 26 || stat == 27
            @modifier = 8
        elsif stat == 28 || stat == 29
            @modifier = 9
        elsif stat > 29
            @modifier = 10
        end
    end
    
    def lightArmor
        equitmentPiece = rand(0...3)
        lightarmor = ["Padded Armor", "Leather Armor", "Studded Leather Armor"]
        returnValue = lightarmor[equitmentPiece]
        returnValue
    end
    
    def mediumArmor
        equitmentPiece = rand(0...5)
        mediumarmor = ["Hide Armor", "Chain Shirt", "Scale Mail", "Breastplate", "Half Plate"]
        returnValue = mediumarmor[equitmentPiece]
        returnValue
    end
    
    def heavyArmor
        equitmentPiece = rand(0...4)
        heavyarmor = ["Ring Mail", "Chain Mail", "Splint", "Plate"]
        returnValue = heavyarmor[equitmentPiece]
        returnValue
    end
    
    def simpleMelee
        weaponPiece = rand(0...11)
        simplemelee = ["Club", "Dagger", "Greatclub", "Handaxe", "Javelin", "Light Hammer", "Mace", "Quarterstaff", "Sickle", "Spear", "Unarmed"]
        returnValue = simplemelee[weaponPiece]
        returnValue
    end
    
    def simpleRange
        weaponPiece = rand(0...4)
        simplerange = ["Light Crossbow", "Darts", "Shortbow", "Sling"]
        returnValue = simplerange[weaponPiece]
        returnValue
    end
    
    def martialMelee
        weaponPiece = rand(0...18)
        martialmelee = ["Battleaxe", "Flail", "Glaive", "Greataxe", "Greatsword", "Halberd", "Lance", "Longsword", "Maul", "Morningstar", "Pike", "Rapier", "Scimitar", "Shortsword", "Trident", "War Pick", "Warhammer", "Whip"]
        returnValue = martialmelee[weaponPiece]
        returnValue
    end
    
    def martialRange
        weaponPiece = rand(0...5)
        martialrange = ["Blowgun", "Hand Crossbow", "Heavy Crossbow", "Longbow", "Net"]
        returnValue = martialrange[weaponPiece]
        returnValue
    end
    
    def barbarians                          #0
        @@gold = 0
        @armorType = rand(0...2)
        if @armorType == 0
            @@armorclass = "Light Armor"
            @@armorequipment = lightArmor
        elsif @armorType == 1
            @@armorclass = "Medium Armor"
            @@armorequipment = mediumArmor
        end
        
        @weaponType = rand(0...4)
        if @weaponType == 0
            @@weaponequipment = simpleMelee
        elsif @weaponType == 1
            @@weaponequipment = martialMelee
        elsif @weaponType == 2
            @@weaponequipment = simpleRange
        elsif @weaponType == 3
            @@weaponequipment = martialRange
        end
        
        (0...2).each do |i|
            @diceRoll = rand(1..4)
            @@gold = @@gold + @diceRoll
        end
        @@gold = @@gold * 10
        
        dieRoll = rand(1..12)
        @@hitpoints = 1 * dieRoll
        @@hitpoints = @@hitpoints + @@constitutionmodifier
    end
    
    def bards                               #1
        @@gold = 0
        @@armorclass = "Light Armor"
        @@armorequipment = lightArmor
        
        @weaponType = rand(0...4)
        if @weaponType == 0
            @@weaponequipment = simpleMelee
        elsif @weaponType == 1
            @@weaponequipment = martialMelee
        elsif @weaponType == 2
            @@weaponequipment = simpleRange
        elsif @weaponType == 3
            @@weaponequipment = martialRange
        end
            
        (0...5).each do |i|
            @diceRoll = rand(1..4)
            @@gold = @@gold + @diceRoll
        end
        @@gold = @@gold * 10
        
        dieRoll = rand(1..8)
        @@hitpoints = 1 * dieRoll
        @@hitpoints = @@hitpoints + @@constitutionmodifier
    end
    
    def clerics                             #2
        @@gold = 0
        @armorType = rand(0...2)
        if @armorType == 0
            @@armorclass = "Light Armor"
            @@armorequipment = lightArmor
        elsif @armorType == 1
            @@armorclass = "Medium Armor"
            @@armorequipment = mediumArmor
        end
        
        @weaponType = rand(0...2)
        if @weaponType == 0
            @@weaponequipment = simpleMelee
        elsif @weaponType == 1
            @@weaponequipment = simpleRange
        end
        
        (0...5).each do |i|
            @diceRoll = rand(1..4)
            @@gold = @@gold + @diceRoll
        end
        @@gold = @@gold * 10
        
        dieRoll = rand(1..8)
        @@hitpoints = 1 * dieRoll
        @@hitpoints = @@hitpoints + @@constitutionmodifier
    end
    
    def druids                              #3
        @@gold = 0
        @armorType = rand(0...2)
        if @armorType == 0
            @@armorclass = "Light Armor"
            @@armorequipment = lightArmor
        elsif @armorType == 1
            @@armorclass = "Medium Armor"
            @@armorequipment = mediumArmor
        end
        
        @weaponType = rand(0...3)
        if @weaponType == 0
            @@weaponequipment = simpleMelee
        elsif @weaponType == 1
            @@weaponequipment = martialMelee
        elsif @weaponType == 2
            @@weaponequipment = simpleRange
        end
        
        (0...2).each do |i|
            @diceRoll = rand(1..4)
            @@gold = @@gold + @diceRoll
        end
        @@gold = @@gold * 10
        
        dieRoll = rand(1..8)
        @@hitpoints = 1 * dieRoll
        @@hitpoints = @@hitpoints + @@constitutionmodifier
    end
    
    def fighters                            #4
        @@gold = 0
        @armorType = rand(0...3)
        if @armorType == 0
            @@armorclass = "Light Armor"
            @@armorequipment = lightArmor
        elsif @armorType == 1
            @@armorclass = "Medium Armor"

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_form.html.erb
<%= form_for @character do |f| %>

  <% if @character.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@character.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :background %><br>
    <%= f.text_area :background %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/characters/background:text.html.erb
<h1>Characters#background:text</h1>
<p>Find me in app/views/characters/background:text.html.erb</p>

app/views/characters/classes:string.html.erb
<h1>Characters#classes:string</h1>
<p>Find me in app/views/characters/classes:string.html.erb</p>

app/views/characters/edit.html.erb
<h1>Editing Character</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<h1>Your characters:</h1>
<h2 style="text-align:left"><%= link_to 'Create a new character?', new_character_path %></h2>

<table>
  <tr>
    <th>Character</th>
    <th>Background</th>
  </tr>
  <% @characters.each do |character| %>
    <tr>
      <td><%= character.name %></td>
      <td><%= character.background %></td>
      <td><%= link_to 'View', character_path(character) %></td>
      <td><%= link_to 'Edit', edit_character_path(character) %></td>
      <td><%= link_to 'Terminate',
                                  character_path(character),
                                  method: :delete,
                                  data: { confirm: 'Are you sure you want to remove this character?' } %></td>
    </tr>
  <% end %>
</table>

app/views/characters/name:string.html.erb
<h1>Characters#name:string</h1>
<p>Find me in app/views/characters/name:string.html.erb</p>

app/views/characters/new.html.erb
<%= form_for :character, url: characters_path do |f| %>
<%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <%= f.label :background %><br>
  <%= f.text_area :background, size: "60x12" %><br>
  <%= f.submit %>
<% end %>
<%= link_to 'Go back!', characters_path %>

app/views/characters/race:string.html.erb
<h1>Characters#race:string</h1>
<p>Find me in app/views/characters/race:string.html.erb</p>

app/views/characters/show.html.erb
<p>
  Your name is... <strong><%= @character.name %></strong>, <br/>
  and you are a <i><%= @character.race %> <%= @character.classes %></i>. <br/>
</p>

<p>
    <strong>Background:</strong> <br />
    Your story is: <%= @character.background %> <br/>
</p>

<p>
  <strong>Condition:</strong> <br/>
  Hit points: ( <%= @character.hitpoints %> )
</p>

<p>
  <strong>Stats:</strong> <br/>
  Strength:
  <%= @character.strength %> ( <%= @character.strengthmodifier %> )<br/>
  Dexterity:
  <%= @character.dexterity %> ( <%= @character.dexteritymodifier %> )<br/>
  Constitution:
  <%= @character.constitution %> ( <%= @character.constitutionmodifier %> )<br/>
  Intelligence:
  <%= @character.intelligence %> ( <%= @character.intelligencemodifier %> )<br/>
  Wisdom:
  <%= @character.wisdom %> ( <%= @character.wisdommodifier %> )<br/>
  Charisma:
  <%= @character.charisma %> ( <%= @character.charismamodifier %> )<br/>
</p>

<p>
    <strong>Equipment:</strong> <br />
    You are trained in <%= @character.armorclass %> usage and thus, have equipped yourself accordingly. With your <%= @character.armorequipment %> donned and <%= @character.weaponequipment %> in hand, you feel like you can handle anything. Sifting through your pockets you find <%= @character.gold %> GP.<br />
</p>


<p><strong>Player Notes and Discussion:</strong><p>
<% @character.comments.each do |comment| %>
  <p>
    Alias:
    <%= comment.commenter %>
  </p>
  <p>
    Note:
    <%= comment.body %>
  </p>
  <p>
    <%= link_to 'Remove Note', [comment.character, comment],
                method: :delete,
                data: {confirm: 'Are you sure you want to remove this note?'} %>
  </p>
<% end %>
<p><strong>Got something to say? Submit here!</strong><p>
<%= form_for([@character, @character.comments.build]) do |f| %>
    <p>
        <%= f.label :alias %><br>
        <%= f.text_field :commenter %>
    </p>
    <p>
        <%= f.label :note %><br>
        <%= f.text_area :body %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

<%= link_to 'Go back!', characters_path %>